### PR TITLE
Use more specific mshtml interface

### PR DESCRIPTION
**Pull request by leowalkling**
IHTMLDocument2 has only very limited support for filtering operations, supported by the actual object. Use the most specific interface instead.

### CODE REVIEW

**Comment by alexis-** [comment]
Do you know which version of IE does this interface correspond to ?

**Comment by leowalkling** [comment]
I saw the same GUID and coclass name in both in my local Win 8.1 SDK and in the latest Win 10 SDK.
Indeed, the differences between those versions of the IDL file did not include any direct changes to the IHTMLDocument* interfaces.
Note that while this looks like a class, you can use it as interface for the purpose of p/invoke declarations.

**Comment by alexis-** [comment]
> I saw the same GUID and coclass name in both in my local Win 8.1 SDK and in the latest Win 10 SDK.

What does that tell us about the IE version ? I'm concerned about the retro-compatibility with people running SM on older versions of Windows.

> Indeed, the differences between those versions of the IDL file did not include any direct changes to the IHTMLDocument* interfaces.

Could you clarify which version of IHTMLDocument* did you compare HTMLDocument with ?

And in case it the latest can we assume that HTMLDocument is merely a copy of the latest version of IHTMLDocument* ?

Information on this topic is scarce.

> Note that while this looks like a class, you can use it as interface for the purpose of p/invoke declarations.

I'm confused, what are we talking about here ? I thought we were discussing the COM interface. I don't remember noticing any `DllImport` in the declarations.

**Comment by leowalkling** [comment]
> > I saw the same GUID and coclass name in both in my local Win 8.1 SDK and in the latest Win 10 SDK.
> 
> What does that tell us about the IE version ? I'm concerned about the retro-compatibility with people running SM on older versions of Windows.
> 
I also checked with Version 6.0 (Win XP), using the type library mshtml.tlb from [exefiles.com](https://www.exefiles.com/en/tlb/mshtml-tlb/) . In that type library, the GUID is the same, as is the name, but the set of methods is different (mostly smaller).

> > Indeed, the differences between those versions of the IDL file did not include any direct changes to the IHTMLDocument* interfaces.
> 
> Could you clarify which version of IHTMLDocument* did you compare HTMLDocument with ?
> 
> And in case it the latest can we assume that HTMLDocument is merely a copy of the latest version of IHTMLDocument* ?
> 
The IHTMLDocument<N> are not a hierarchy, they don't inherit from one another.
HTMLDocument contains a number of IHTMLDocument<N> interfaces and some others.
In WinSDK 8.1 and 10, IHTMLDocument8 is the last one of them, but I couldn't check with Windows SDK 7 (XP).

> > Note that while this looks like a class, you can use it as interface for the purpose of p/invoke declarations.
> 
> I'm confused, what are we talking about here ? I thought we were discussing the COM interface. I don't remember noticing any `DllImport` in the declarations.

It's in L91.

**Comment by leowalkling** [comment]
@alexis- 
Merge conflicts resolved.

**Comment by alexis-** [comment]
Sorry I had to rewrite the history due to an issue with [Nerdbank.GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning) which didn't leave me with any other choice

**Comment by alexis-** [comment]
That being said, I can just copy and paste your changes as they are minimal.
You don't need to bother with rebasing your change. Let me know if that's a satisfactory solution for you

**Pull request closed without merging**
